dist: precise
language: java
jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

install:
  - travis_wait mvn -q -Pdev,dist install -DskipTests

script:
  - mvn -Dsurefire.forkCount=4 -Pdev verify
